
CREATE DATABASE IF NOT EXISTS db_usuario;
CREATE DATABASE IF NOT EXISTS db_categoria;
CREATE DATABASE IF NOT EXISTS db_producto;
CREATE DATABASE IF NOT EXISTS db_inventario;
CREATE DATABASE IF NOT EXISTS db_carrito;
CREATE DATABASE IF NOT EXISTS db_pedido;
CREATE DATABASE IF NOT EXISTS db_pagos;
CREATE DATABASE IF NOT EXISTS db_envio;
CREATE DATABASE IF NOT EXISTS db_notificacion;
CREATE DATABASE IF NOT EXISTS db_reporte;
